### PR TITLE
Rol check gradient

### PR DESCRIPTION
**Pull request by acsokolow**
Fixed workflow in XMLGenerator to allow ROL Check Gradient
Added 2 rol specific optimization parameter commands in XMLgen.
Fixed Check Gradient function call in ROL Interface class.
Refactored the separate header files for ROL BC/LC/AL into the parent class.
Added 2 regression tests of ROL using Proxy tests, and 3 examples using PA.

### CODE REVIEW

**Comment by ralberd** [comment]
I misunderstood why you had the ESP tests commented out in CMakeLists.txt so I took them out. I placed them back now that I realize you want to keep them around.

**Comment by ralberd** [comment]
Adam, I fixed a couple of typos and removed files that seemed like temporaries. Take a look and let me know if you approve. I'll merge it in if so.

**Comment by acsokolow** [comment]
Looks good to me - some of the indents that you removed show up missing in my version. I'm not sure what's going on there, but maybe some issue with tabs in the different viewers.

**Review by ralberd — APPROVED** [review]

**Comment by shardest** [comment]
Can we delete Plato's gradient checker now?

**Comment by brettclarkgithub** [comment]
It seems like if we can do everything with the ROL one now that we could do with Plato's it should be fine.

From: shardest ***@***.***>
Sent: Friday, August 19, 2022 9:18 AM
To: platoengine/platoengine ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [EXTERNAL] Re: [platoengine/platoengine] Rol check gradient (PR #351)


Can we delete Plato's gradient checker now?

-

**Comment by ralberd** [comment]
Are there other tests that haven't been converted over? I thought I made an MPCs one.

**Comment by ralberd** [comment]
It looks like all the FD check tests in regression still use Plato's checker?

**Comment by acsokolow** [comment]
Sticking to the story - I added ROL gradient check capability and created new tests for it. 

It is straight forward to check the gradient for any problem using ROL. The FD regression tests do not use the XMLgenerator, so will take some more careful hands on editing. It might be good to identify specific apps/objectives/constraints that we want to create example problems for and check their gradients. 

New story?

**Comment by ralberd** [comment]
Yeah I think that should be its own story

**Comment by shardest** [comment]
Sounds good.

**Comment by acsokolow** [comment]
The examples & regressions in the "GradientCheck" folder use Python to confirm that the error in the gradient has a similar V shape to the gold file (within tolerance). This pattern can be re-used for all of the proposed examples.

**Pull request merged**
