### PR TITLE
Tet10

### PR DESCRIPTION
**Pull request by jrobbin**
All tests pass.

### CODE REVIEW

**Comment by ralberd** [comment]
Hey Josh, I assume that you have the other element tests commented out in the CMakeLists.txt file because they need a better solver than AmgX? Were you able to get them to run at all?

**Comment by jrobbin** [comment]
I need to pause the element work to get Tpetra working with PA, so I won't be committing the new element types just yet.  I'll turn these back on when I commit the new elements.  The Hex8 version runs pretty well, but Tet10 and Hex27 take forever to solve with AmgX.
________________________________
From: ralberd ***@***.***>
Sent: Tuesday, April 26, 2022 5:33 PM
To: platoengine/platoengine ***@***.***>
Cc: Robbins, Joshua ***@***.***>; Author ***@***.***>
Subject: [EXTERNAL] Re: [platoengine/platoengine] Tet10 (PR #296)


Hey Josh, I assume that you have the other element tests commented out in the CMakeLists.txt file because they need a better solver than AmgX? Were you able to get them to run at all?

**Comment by ralberd** [comment]
So this PR is just the higher order element scaffolding and tests and the concrete implementation will be merged later?

**Comment by jrobbin** [comment]
Yep.  It's IO for the Hex27 and Tet10 elements and a few (disabled) tests.  I wanted to merge these changes (the new element IO in particular) before I separate out LightMP.
________________________________
From: ralberd ***@***.***>
Sent: Tuesday, April 26, 2022 5:39 PM
To: platoengine/platoengine ***@***.***>
Cc: Robbins, Joshua ***@***.***>; Author ***@***.***>
Subject: [EXTERNAL] Re: [platoengine/platoengine] Tet10 (PR #296)


So this PR is just the higher order element scaffolding and tests and the concrete implementation will be merged later?

**Comment by ralberd** [comment]
Got it. Thanks!

**Review by ralberd — APPROVED** [review]

**Pull request merged**
