### PR TITLE
adds stl output to stand alone extract_iso executable

### PR DESCRIPTION
**Pull request by rviertel**

### CODE REVIEW

**Comment by rviertel** [comment]
There is only one new commit, 35b9465, the rest are all merge commits from the release branch because several hot-fixes were done by branching off develop instead of release. This is not a problem, just an explanation of why there are so many commits

**Review by brettclarkgithub — APPROVED** [review]
Ryan, do we need to put a couple of regression tests in for this?

**Comment by rviertel** [comment]
Yeah you're right we should. I'll add those in tomorrow

Ryan Viertel
Sandia National Labs, Dept. 01543
Simulation Modeling Sciences
P.O. Box 5800 MS 0897
Albuquerque, NM 87185-0897
(801)669-4887 (cell)
***@***.***
________________________________
From: brettclarkgithub ***@***.***>
Sent: Wednesday, July 14, 2021 5:06 PM
To: platoengine/platoengine ***@***.***>
Cc: Viertel, Ryan ***@***.***>; Author ***@***.***>
Subject: [EXTERNAL] Re: [platoengine/platoengine] adds stl output to stand alone extract_iso executable (#86)


Merged #86<https://github.com/platoengine/platoengine/pull/86> into develop.

**Comment by rviertel** [comment]
Hey Brett,

I'm working on adding a regression test, but I'm not sure how to verify the answer at the end.  Is there a good way to diff stl files with Plato or Trilinos? Or a way to change them to text at least?


Thanks,

Ryan Viertel
Sandia National Labs, Dept. 01543
Simulation Modeling Sciences
P.O. Box 5800 MS 0897
Albuquerque, NM 87185-0897
(801)669-4887 (cell)
***@***.***
________________________________

**Comment by brettclarkgithub** [comment]
I don’t suppose there is an option in the iso extract code for writing it out in ASCII instead of binary…

From: Ryan Viertel ***@***.***>
Sent: Tuesday, July 20, 2021 5:15 PM
To: platoengine/platoengine ***@***.***>
Cc: Clark, Brett W ***@***.***>; State change ***@***.***>
Subject: [EXTERNAL] Re: [platoengine/platoengine] adds stl output to stand alone extract_iso executable (#86)

Hey Brett,

I'm working on adding a regression test, but I'm not sure how to verify the answer at the end. Is there a good way to diff stl files with Plato or Trilinos? Or a way to change them to text at least?


Thanks,

Ryan Viertel
Sandia National Labs, Dept. 01543
Simulation Modeling Sciences
P.O. Box 5800 MS 0897
Albuquerque, NM 87185-0897
(801)669-4887 (cell)
***@***.***
________________________________

**Pull request merged**
